### ISSUE TITLE
Top scroll bar not loading

### ISSUE THREAD

**Issue by Blackbaud-SpencerMurphy** [blackbaud/skyux-grids#104]
### Expected behavior
The top scrollbar should load on initial page load and when columns are updated

### Actual behavior
In our spa, the top scrollbar does not load until the screen has been resized. The scrollbar also doesn't load when additional columns are selected that would make the bottom scrollbar appear. Troubleshooting a little with Trevor, it looks like it's missing some change detection either with our data provider or with the columns.

### Steps to reproduce

1. Load a large grid (such as the permissions spa user list) that uses a data provider
2. Notice the top scroll bar doesn't show up

1. Load a grid with not all columns selected (but with enough unselected columns to cause the scrollbars to show when all selected)
2. Add unselected columns
3. Notice top scroll bar doesn't show up

### Severity
Cosmetic

### Impact
Customers are already used to there not being a top scrollbar on our grid. Wouldn't have noticed it myself had I not known about it.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.5.3`
