### ISSUE TITLE
Sticky column settings cause grid to load twice upon initial page load

### ISSUE THREAD

**Issue by Blackbaud-KrisMahon** [blackbaud/skyux-grids#134]
### Expected behavior
When a user has sticky settings for a list that contain saved column ids, the grid should only fetch the list data once upon initial load.

### Actual behavior
When a user has sticky settings for a list that contain saved column ids, the grid makes two calls to fetch data upon initial load.  The first call appears to be made as if no sticky settings are present (ie: just using default settings and column ids), and the second call appears to made after the sticky settings have loaded and the column ids are updated based on the loaded sticky settings (this causes a change event to occur on the selected column ids which re-fetches the list data).

### Steps to reproduce
1. Add a `sky-list` and `sky-list-view-grid` to a page, and make sure it uses a `settingsKey` that is configured in the ui config service.  Also, configure the `sky-list` to use a `dataProvider`.  Also, add the column selector to the list.
2. The first time you load the list, you will see it only calls the `dataProvider` once.
3. Using the column selector, change which columns are selected.  The list will update properly with only a single call to the `dataProvider`.
4. Reload the entire page, and notice that now the `dataProvider` gets called twice - once before and once after loading the column settings.

### Severity
Medium

### Impact
Medium - It is just making two calls to our endpoints instead of one and possibly causing a little latency in loading the lists.

[AB#1535504](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1535504)

**Comment by blackbaud-GavinNicol** [comment]
It seems as this bug may have bigger issues then just causing the list to load twice. We're seeing issues where the 1st request with the default columns may come back after the 2nd request with the columns that come from sticky settings which can lead to some columns showing up without the expected data since the columns from the second request are shown with the data from the first request.
