### ISSUE TITLE
Grid Event selectedColumnIdsChange is not getting executed for the first time

### ISSUE THREAD

**Issue by Blackbaud-SahilKhurana** [blackbaud/skyux-grids#141]
### Expected behavior
`selectedColumnIdsChange `event should get fired when we change the column order in grid.

### Actual behavior
`selectedColumnIdsChange `is not getting fired for first time when we change the column order, but is getting fired after 2nd time.
### Steps to reproduce
1. Create a grid and implement selectedColumnIdsChange event.
2. try to change the column order by dragging the column,
3. selectedColumnIdsChange event will not get fired for first change in column order.

### Severity
High

### Impact
It is impacting our use case, where we are performing some activities based on column order.

[AB#1535489](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1535489)

**Comment by Blackbaud-AlexKingman** [comment]
This is fixed in `4.0.2`.
