### ISSUE TITLE
Column Header Appears Blank When Column Width Not Wide Enough To Show Text

### ISSUE THREAD

**Issue by justineshaw** [blackbaud/skyux-grids#144]
### Expected behavior
Column Header should show an ellipse when the column width is not wide enough to show text.
### Actual behavior
Column Header appears blank when the column width is not wide enough to show text.
### Steps to reproduce
1. Go to the demo
2. Make the columns smaller by dragging
3. Observe the column header text appears blank

![image](https://user-images.githubusercontent.com/43732195/89545689-ad120f00-d7d1-11ea-9f5d-fa217754e525.png)

### Impact

[AB#1545540](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1545540)

**Comment by Blackbaud-TrevorBurch** [comment]
In `4.0.3`
