### ISSUE TITLE
Inline-Delete Causes UI Issue

### ISSUE THREAD

**Issue by justineshaw** [blackbaud/skyux-grids#145]
### Expected behavior
`sky-inline-delete` should work with `sky-list-view-grid` so when I go to use inline-delete in a grid, there should be no change to the column headers.
### Actual behavior
using inline-delete in a grid causes a UI issue where a column is created
### Steps to reproduce
1. Load a fresh instance of grid (don't drag any column headers to change width or bug won't occur)
2. Use context menu to open inline-delete
3. Notice the new column that appears which seems to house the inline-delete
![image](https://user-images.githubusercontent.com/43732195/89564740-734e0200-d7eb-11ea-8dc5-b483a596be76.png)

### Impact

[AB#1546321](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1546321)

**Comment by Blackbaud-TrevorBurch** [comment]
In `4.0.6`
