### ISSUE TITLE
Grid columns will truncate text when text is inside sky-label

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux-grids#27]
### Expected behavior
If grid has room, the column width should expand to fit the width of its contents.

### Actual behavior
If the contents have a sky-label, the label will be truncated.

### Plunker
https://plnkr.co/edit/WHNYURuARQV68Op38EDA?p=preview

### Impact
Current workaround is to assign a column width.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.1.1`
