### ISSUE TITLE
Add support for programmatically selecting rows by ids.

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux-grids#37]
Use case: user selects a course of students from a list. They then click an add button which adds the students from that course to the list. They may do this multiple times, but they will want the checkboxes selected by default as new students are added to the list. We need a way for consumers to programmatically set these selected rows.

Some work has already been done on this. See `multiselect-select-by-id` branch.

Related (list-view-grids version):
blackbaud/skyux-list-builder#57

**Comment by christinebrandel** [comment]
In a similar fashion, I'd like to be able to clear out the selected items after taking a bulk action.   Even though I'm providing new data to the grid, internally the items are still selected. The only way I can clear this now is by reloading the page.
