### ISSUE TITLE
Grid columns cannot be resized on mobile

### ISSUE THREAD

**Issue by MatthewMazaika** [blackbaud/skyux-grids#40]
### Expected behavior
Grabbing and dragging column dividers on mobile would allow resizing 
### Actual behavior
Column dividers appear to get selected, but cannot resize
### Steps to reproduce
Open page with grid on mobile device (or chrome debug tools)

**Comment by Blackbaud-AlexKingman** [comment]
@Blackbaud-ToddRoberts Do we have any design specs on how this would work in a mobile environment?

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.1.6`
