### ISSUE TITLE
Empty sky-grid and sky-list-view-grid render with scroll bar in Edge

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux-grids#42]
@Blackbaud-MitchellThomas commented on [Mon Sep 10 2018](https://github.com/blackbaud/skyux2/issues/1972)

### Expected behavior
In Microsoft Edge, an empty sky-list-view-grid renders the same as a list with data except that the list is empty.

### Actual behavior
In Edge, the empty list has a scroll bar that is ugly and obscures the column names.

### Steps to reproduce
Create a sky-list-view-grid with no supplied data. View in Edge.
![image](https://user-images.githubusercontent.com/9661547/45301706-76e18d00-b4df-11e8-818c-a982e0862c80.png)

### Plunker
https://plnkr.co/edit/SrjiXcYnFXODkZFqB9jw?p=preview

### Severity
It seems to have been an issue for a while, at least since May, but it only affects empty grids in Edge in a cosmetic way.

### Impact
All empty grids in Edge.

### Notes
I believe it is differences in how Edge and Chrome (or others) render an empty `<tbody>`. If I mark the empty `<tbody>` with `display:none`, the scroll disappears. If I put an empty `<tr>` in it, it also disappears but displays a little space.

Would it be valid to just `*ngIf` that tbody to not display if the length of the supplied data is 0?

**Comment by Blackbaud-TrevorBurch** [comment]
This appears to be fixed via Microsoft Edge 79. Please let us know if you're still seeing this after updating Edge to 79
