### ISSUE TITLE
Horizontal scroll bar appears on sky-list-view-grid

### ISSUE THREAD

**Issue by Blackbaud-VanesaiXiong** [blackbaud/skyux-grids#50]
### Expected behavior
1. Grid loads more rows/records/data
2. Vertical scroll bar appears in browser
3. Grid adjusts column size(s) to compensate for vertical scroll bar

### Actual behavior
1. Grid loads more rows/records/data
2. Vertical scroll bar appears in browser
3. Grid does not adjust and instead a horizontal scroll bar is displayed

### Steps to reproduce
1. Have a grid that does not render on page load
2. Grid is contained in a sky-tab (maybe optional, but applies to our situation)
3. Grid renders, but the page should not exceed window height
3.1 Grid should have data that is small enough to fit even with an added scrollbar
4. Grid loads more data, until page exceeds window height

### Plunker
[Link](https://plnkr.co/edit/mZzBS4Es7eh2mKi72Wn6?p=preview)
1. Activate "Tab with grid"
2. Click "Get started"
3. Open the column selector (required for plunker, not needed for our spa)
4. Choose one  or more columns, and apply changes (required for plunker, not needed for our spa)
5. Click "Load more" until page exceeds window height

### Spa
[Repo](https://blackbaud.visualstudio.com/Products/Products%20Team/_git/skyux-spa-volunteers?path=%2Fsrc%2Fapp%2Fvolunteer-home%2Ftabs%2Fvolunteer-home-volunteers-tab%2Fvolunteer-home-volunteers-tab.component.html&version=GBmaster)

### Severity
1. Low

### Impact
1. Informational

**Comment by Blackbaud-AlexKingman** [comment]
The impact of this issue is so low, and fixing it might also have some considerable tech overhead. Closing. If you feel this is still an issue that needs resolved, please re-open.
