### ISSUE TITLE
Multiselect button vertically aligned to top

### ISSUE THREAD

**Issue by Blackbaud-MichaelFelak** [blackbaud/skyux-grids#60]
### Expected behavior
The multiselect button should be vertically aligned in the center of the grid-row.

### Actual behavior
The multiselect button is vertically aligned at the top of the grid-row. Since the context menu is included in this grid, it expands the row size, therefore showing the checkbox as aligned too high.

### Steps to reproduce
enable multi select in a sky-list-view grid.
include a context menu component in the grid (or anything of varying height)

![image](https://user-images.githubusercontent.com/18555725/58984563-5d881b80-87a7-11e9-867a-bddc1b54ea62.png)

### Severity
low

### Impact
cosmetic

**Comment by Blackbaud-AlexKingman** [comment]
@Blackbaud-MichaelFelak This seems to be working today, as of version `3.4.0` - the multiselect box is vertically aligned to the center of the row, no matter the height of the row's content. If you still feel like this is an issue, please reopen with some specifics on how to replicate. Thanks!

Closing for now.
