### ISSUE TITLE
Locked grid-column allows other columns to be dragged before it

### ISSUE THREAD

**Issue by Blackbaud-TomSisson** [blackbaud/skyux-grids#67]
### Expected behavior
Documentation indicates expected behavior as: _If set to true, then users cannot drag the column to another position and or drag other columns before the locked column._ 

### Actual behavior
Other columns can be dragged in front of a locked column.

### Steps to reproduce
- Add the `[locked]="true"` property onto a `sky-grid-column`
- Drag and drop other columns in front of this locked column

The Name column in the first grid here is locked but you can move other columns before it:
https://stackblitz.com/edit/angular-5q8gzq?file=src/app/demo/grid-demo.component.html

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.2.1`
