### ISSUE TITLE
Locked grid-column can be moved by the sorting caret

### ISSUE THREAD

**Issue by Blackbaud-TomSisson** [blackbaud/skyux-grids#68]
### Expected behavior
Documentation indicates expected behavior as: _If set to true, then users cannot drag the column to another position and or drag other columns before the locked column._ 

### Actual behavior
Locked columns can be dragged around by the sorting caret.

### Steps to reproduce
- Add the `[locked]="true"` property onto a `sky-grid-column`
- Click on the column name to sort
- Click on the sort caret for the locked column and drag elsewhere in the grid

The Name column in the first grid here is locked but you can move it by the sort caret:
https://stackblitz.com/edit/angular-5q8gzq?file=src/app/demo/grid-demo.component.html

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.2.1`
