### ISSUE TITLE
SkyGridComponent > getTableHeaderClassNames: undefined is not an object (evaluating 'n.locked')

### ISSUE THREAD

**Issue by Blackbaud-KrisMahon** [blackbaud/skyux-grids#74]
### Expected behavior
List/grid should not fail trying to display.

### Actual behavior
This issue has appeared in our monitoring from time to time, but we are unable to duplicate it.  It appears to happen on a basic `sky-list` component with a handful of columns.  We are not using the colulmn chooser on these lists, and we are not hooked into the persisted column settings.

```
undefined is not an object (evaluating 'n.locked') at getTableHeaderClassNames
```

It appears to be failing in `SkyGridComponent.getTableHeaderClassNames` at [this location](https://github.com/blackbaud/skyux-grids/blob/4f7db26626afc2100e2c58fcf0b830abd6cdb1f6/src/app/public/modules/grid/grid.component.ts#L325) because the `column` appears to be `undefined`.

### Steps to reproduce
Unable to reproduce, found in our monitoring.  The monitoring did report the following information, but we've been unable to duplicate or determine if iOS is the reason behind the failure.

- iPhone
- iOS 12.4
- Mobile Safari 12.1

### Severity
Medium(?) - we've seen the issue pop-up a few times, but not a lot.

### Impact
Causes entire SPA to crash.

**Comment by Blackbaud-KrisMahon** [comment]
We just encountered another very similar issue on a different `sky-list` component (this one uses filters, column chooser, and persisted settings).  It appears the issue is also in `SkyGridComponent` and may be related.  In this case it appears that somehow the grid is missing the column for the particular index and then it tries to set `.width` on the `undefined` column.

```
Unable to set property 'width' of undefined or null reference at n.prototype.resizeColumnByIndex
```

In this case, our logging indicated the issue was coming from Internet Explorer 11.0.  This issue also causes the entire SPA to crash.

**Comment by blackbaud-elizabethsmith** [comment]
This issue continues to come up in our monitoring, and it seems to be happening with higher frequency. Another example of how this has manifested is `Cannot read property 'locked' of undefined at n.getTableHeaderClassNames`. 
Again, this causes the entire SPA to crash.

**Comment by Blackbaud-SteveBrush** [comment]
Update: we've pulled this into this week's sprint. Stay tuned!

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.5.1`
