### ISSUE TITLE
Grid header should be pinned

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux-grids#84]
### Expected behavior
Grid header is pinned so that user can see column headings when scrolling down the list.

### Actual behavior
Headers scroll with the page so the user loses context of what they are looking at.

**Comment by Blackbaud-ToddRoberts** [comment]
From FE NXT team.

They use a lot of grids for long lists of data so this is a particularly important problem for them.

**Comment by Blackbaud-DanMiller** [comment]
This is supported with ag-grid.
