### ISSUE TITLE
Grid should have a horizontal scrollbar at the top of the list

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux-grids#85]
### Expected behavior
There is a scrollbar at the top of the list (eg attached to a pinned grid header #84 ) so that the user can scroll to the right without having to scroll down first.

### Actual behavior
The only horizontal scrollbar is at the bottom of the list so the user has to scroll down to see it. This is particularly problematic when using infinite scroll.

**Comment by Blackbaud-ToddRoberts** [comment]
From FE NXT team.

They use a lot of grids for long lists of data so this is a particularly important problem for them.

**Comment by Blackbaud-VinLanzolla** [comment]
The lack of scrollbar at the top of the list renders infinite scroll useless.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.5.0`
