### ISSUE TITLE
Set host.url property in `skyuxconfig.json` to developer.blackbaud.com

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux-grids#90]
This is so PR comments (like [this one](https://github.com/blackbaud/skyux-grids/pull/89#issuecomment-573202264)) will point to developer.blackbaud.com.

More importantly, when this repo is updated to contain its own documentation, we'll want to use that domain.  This is true for all repos going through that process.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.5.0`
