### ISSUE TITLE
Allow content alignment (left/right at least, center maybe) as a property of grid columns

### ISSUE THREAD

**Issue by Blackbaud-AdamFunderburk** [blackbaud/skyux-grids#92]
Right-aligning numeric data is standard practice, and especially beneficial when any sort of comparison or computation is involved. 

Note: Data entry grid appears to do this to numeric data by default. https://developer.blackbaud.com/skyux/components/data-entry-grid

Another note: `bb-grid` in SKY 1 does allow this option in grid column settings https://skyux.developer.blackbaud.com/components/grids/

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-ToddRoberts Thoughts on this one?

**Comment by Blackbaud-ToddRoberts** [comment]
It seems reasonable to me, vs forcing the consumer to use a templated layout for an alignment shift on simple text.

**Comment by Blackbaud-SteveBrush** [comment]
Closing because this is currently possible using custom cell templates.
