### ISSUE TITLE
Grid scrolling broken

### ISSUE THREAD

**Issue by Blackbaud-TrevorBurch** [blackbaud/skyux-grids#93]
In the _master_ branch but **NOT** yet released the scrolling of a grid that is wider than its parent (or window) is broken. No scroll bar ever appears to allow for grid scrolling.

**Comment by Blackbaud-SteveBrush** [comment]
Tested on Windows Chrome.

**Comment by Blackbaud-AlexKingman** [comment]
Reverted sticky headers to fix this issue. See #94
